# The default West manifest file to be used for Zephyr.
west:
  url: https://github.com/tejlmand/west
  revision: feature_west_reset


manifest:
  defaults:
    remote: upstream
    revision: master

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos
    - name: mcu-upstream
      url-base: https://github.com/JuulLabs-OSS

  projects:
    - name: zephyr
      sha: 7734627215d094754a4f097b255f84ffe4391da3
      revision: master
    - name: mcuboot
      remote: mcu-upstream
      revision: 4d2052519505982c99679268c9f4390c195ccb10
